### ISSUE TITLE
mini.files broken state after :q!

### ISSUE THREAD

**Issue by Pytness** [echasnovski/mini.nvim#1769]
### Contributing guidelines

- [x] I have read [CONTRIBUTING.md](https://github.com/echasnovski/mini.nvim/blob/main/CONTRIBUTING.md)
- [x] I have read [CODE_OF_CONDUCT.md](https://github.com/echasnovski/mini.nvim/blob/main/CODE_OF_CONDUCT.md)
- [x] I have updated 'mini.nvim' to latest version of the `main` branch

### Module(s)

mini.files

### Neovim version

0.12 (!at least latest Nightly build!)

### Description

Using `:q!` inside `mini.files` window after opening a file with it seems to leave `mini.files` in a broken state and unable to open the window again.

After taking a look and tinkering a bit, I managed to somewhat fix it (I haven't tested it enough nor I know the code well enough):

```diff
:100644 100644 94c603f5 00000000 M	lua/mini/files.lua

diff --git a/lua/mini/files.lua b/lua/mini/files.lua
index 94c603f5..67343691 100644
--- a/lua/mini/files.lua
+++ b/lua/mini/files.lua
@@ -779,6 +779,27 @@ MiniFiles.open = function(path, use_latest, opts)
   -- Get explorer to open
   local explorer
   if use_latest then explorer = H.explorer_path_history[path] end
+
+  if explorer ~= nil then
+    -- check if explorer is still valid
+    local is_visible = H.explorer_is_visible(explorer)
+
+    if not is_visible then
+      explorer.windows = {}
+
+      local views = explorer.views
+
+      for _, view in ipairs(views) do
+        local buf_id = view.buf_id
+
+        if vim.api.nvim_buf_is_valid(buf_id) then
+          H.buffer_delete(buf_id)
+          view.buf_id = H.buffer_create(view.path, explorer.opts)
+        end
+      end
+    end
+  end
+
   explorer = explorer or H.explorer_new(path)
 
   -- Update explorer data. Don't use current explorer's data to allow more
```

It seems that the buffers get unlisted and dont get handled.

### Reproduction

1. `:lua require('mini.files').open()`
2.  Open file using mini.files
3.  `:lua require('mini.files').open()`
4.  `:q!` inside `mini.files` window

This seems to leave `mini.files` in a broken state, making `:MiniFiles.open()` not open the window anymore.

**Comment by Pytness** [comment]
By the way, the second step is important:

> 1. :lua require('mini.files').open()
> 2. Open file using mini.files
> 3. :lua require('mini.files').open()

Using `:q!` without opening a file with `mini.files` or with an already opened buffer will **not** brick it.

**Comment by echasnovski** [comment]
Yes, I can reproduce this after looking at screencast.

> By the way, the second step is important:

This is not only important, but it needs to be with `go_in_plus` (by pressing `L`). I'll take a look.

**Comment by Pytness** [comment]
I managed to reproduce it with `go_in` too.

Since the keymaps _map_ directly to the functions, i will write it in lua (which i tested too):
```lua
local m = require('mini.files')                                                                                                                                                                                  
m.open()                                                                                                                                                                                                         
m.go_in()                                                                                                                                                                                                        
m.close()                                                                                                                                                                                                        
m.open()                                                                                                                                                                                                         
vim.api.nvim_feedkeys(':q!', 'n', true)                                                                                                                                                                      
m.open()
```

Here is the one liner:
```lua
:lua local m = require('mini.files'); m.open(); m.go_in(); m.close(); m.open(); vim.api.nvim_feedkeys(':q!', 'n', true); m.open();
```

Seems to me in the combination of `go_in` and `close`, which go_in_plus seems (to me) to also do.

**Comment by basilgood** [comment]
With this setup from @MariaSolOs your problem will be fixed:
```lua
  vim.keymap.set('n', '-', function()
    local bufname = vim.api.nvim_buf_get_name(0)
    local path = vim.fn.fnamemodify(bufname, ':p')
    if path and vim.uv.fs_stat(path) then
      require('mini.files').open(bufname, false)
    end
  end)
```
I tested the quit from `mini.files` with `:q!` and opening it again several times and it behaves normally.
This configuration is also useful when opening a file, but not from `mini.files`, because it will open `mini.files` where you are and not in the root of the project. It will behave like vinegar.
Just change the keymap to your keymap.
Thanks @echasnovski for the nice work.

**Comment by echasnovski** [comment]
This should now be resolved on latest `main`.

The issue was indeed that `close()` was doing nothing if there was no visible windows (as after `:q!` without enabled preview) and that is why I wasn't able to reproduce this initially (because I had enabled  preview). And thus resuming previously opened explorer resulted in some issues.

The reason [this solution](https://github.com/echasnovski/mini.nvim/issues/1769#issuecomment-2848381432) worked was because it explicitly didn't use previously opened explorer state.

**Comment by MariaSolOs** [comment]
> The reason [this solution](https://github.com/echasnovski/mini.nvim/issues/1769#issuecomment-2848381432) worked was because it explicitly didn't use previously opened explorer state.

@echasnovski And so there should be no need to have those checks around `MiniFiles.open()` anymore?

**Comment by echasnovski** [comment]
> > The reason [this solution](https://github.com/echasnovski/mini.nvim/issues/1769#issuecomment-2848381432) worked was because it explicitly didn't use previously opened explorer state.
> 
> [@echasnovski](https://github.com/echasnovski) And so there should be no need to have those checks around `MiniFiles.open()` anymore?

If I understand correctly, the checks are about making sure that first argument to `open()` is a valid path. That is, to be able to press `-` even inside buffers for not actual file path.

This should have nothing to do with the merged fix, which could be observed only if the *second* argument is `true`.

**Comment by Pytness** [comment]
I believe this is still an issue. I havent yet been able to consistently reproduce it, but it seems its the same as before, but you have to open it and `:q` a couple of times before it breaks. 

Observed on f37f79a (the fix) and on 1b32a3f (latest commit on main atm)

**Comment by echasnovski** [comment]
> I believe this is still an issue. I havent yet been able to consistently reproduce it, but it seems its the same as before, but you have to open it and `:q` a couple of times before it breaks.

I can not reproduce. If there'll be consistent reproduction steps, I'll take a look. But using `:quit` it is still *not* recommended.
